name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"
  
jobs:
  steps:
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply output changes

branding:
  icon: "mic"
  color: "purple"
