name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

- name: Commit files
      id: commit
      run: |
        git config --local user.email "eugene.vinakov@gmail.com"
        git config --local user.name "Eugene Vinakov"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add output.txt" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: eu-genes/hello-github-actions@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}

branding:
  icon: "mic"
  color: "purple"
